// ── Spelling, punctuation and grammar ─────────────────────────────────────
//
// Quest's English paper is twenty questions: twelve on the reading passage
// and EIGHT on spelling, punctuation and grammar. That is 40% of the paper.
// Bexley's own guidance says the verbal paper contains "questions testing two
// of the following areas: spelling, punctuation or grammar".
//
// This file is the authored half of that. Like vocab.js it cannot be proved
// correct by machine, only checked for structure, so tools/spag-test.js
// checks what it can and names what it cannot.
//
// Four banks, matching four Quest question shapes:
//
//   MISTAKES   "Which part of the sentence contains a mistake?" with a
//              "No mistake" option, because Quest includes clean sentences
//              and a child who never meets one learns to always find a fault.
//   PUNCTUATED "Which sentence is punctuated correctly?"
//   COMMAS     "After which word should a comma be added?"
//   GRAMMAR    Grammatical word choice, as opposed to the vocabulary choice
//              already covered by SENTENCES in vocab.js.
//
// The errors are the ones Year 5 and 6 children actually make: agreement,
// homophones, past participles, apostrophes, double negatives, and commas
// after a fronted adverbial. They are not exotic.

/**
 * [parts, badIndex, whatIsWrong]
 * badIndex is -1 when the sentence is correct as it stands.
 */
export const MISTAKES = [
  // The position of the faulty part is deliberately spread. First draft put
  // the error in part A or B in 21 of 26 items, which teaches a child to look
  // at the front of the sentence and stop. tools/spag-test.js now asserts the
  // spread, because the guessability leak is invisible when you read the
  // items one at a time.
  [['My sister and me', 'walked to the shop', 'to buy some milk', 'for breakfast.'], 0,
    'It should be "my sister and I", because they are the ones doing the walking.'],
  [['Me and my brother', 'built a den', 'in the woods', 'behind our house.'], 0,
    'It should be "My brother and I". Try the sentence without "my brother".'],
  [['Your going to be', 'late for school', 'if you do not', 'leave now.'], 0,
    '"Your" shows belonging. The words needed are "You\'re", short for "you are".'],
  [['We seen the fireworks', 'from the top', 'of the hill', 'above the town.'], 0,
    'It should be "We saw". "Seen" needs "have" or "had" in front of it.'],
  [['Their playing football', 'in the park', 'until it gets', 'too dark to see.'], 0,
    '"Their" shows belonging. The word needed is "They\'re", short for "they are".'],
  [['I have wrote', 'a letter', 'to my grandmother', 'every week this year.'], 0,
    'After "have" the word is "written", not "wrote".'],

  [['The group of children', 'were waiting', 'by the gate', 'for the coach.'], 1,
    'The subject is "the group", which is singular, so it should be "was waiting".'],
  [['The cat washed', 'it\'s paws', 'carefully', 'in the sunshine.'], 1,
    '"It\'s" is short for "it is". The possessive form has no apostrophe: "its paws".'],
  [['The books on the shelf', 'was covered', 'in a thick layer', 'of dust.'], 1,
    'The subject is "the books", which is plural, so it should be "were covered".'],
  [['Everyone in the class', 'have finished', 'their painting', 'already.'], 1,
    '"Everyone" is singular, so it should be "has finished".'],
  [['The teacher asked', 'who\'s bag', 'had been left', 'in the corridor.'], 1,
    '"Who\'s" is short for "who is". The possessive is "whose bag".'],
  [['She did not see', 'nothing at all', 'through the window', 'in the dark.'], 1,
    'This is a double negative. With "did not" it should be "anything at all".'],

  [['We could hear', 'the dog barking', 'from over their', 'by the fence.'], 2,
    '"Their" shows belonging. The word needed is "there", meaning that place.'],
  [['The weather was', 'far too cold', 'for us to sat', 'outside at lunchtime.'], 2,
    'After "to" the word is "sit". "Sat" is the past tense.'],
  [['I should have', 'gone to bed', 'much more earlier', 'than I did.'], 2,
    '"Earlier" already means more early, so "more" should not be there.'],
  [['The parcel arrived', 'on Tuesday morning', 'but it was to heavy', 'for me to lift.'], 2,
    'The word meaning excessively is "too", with two letter o\'s.'],
  [['My friend told me', 'that the museum', 'is more busier', 'on a Saturday.'], 2,
    '"Busier" already compares, so "more" should not be there.'],
  [['She put the books', 'on the shelf', 'that her and I', 'had built together.'], 2,
    'It should be "she and I", because they are the ones who built it.'],

  [['The three girls', 'walked home together', 'carrying the heavy bags', 'of there shopping.'], 3,
    '"There" means that place. The word showing belonging is "their".'],
  [['We packed our bags', 'on Friday evening', 'and set off early', 'to visit my aunt in bristol.'], 3,
    'Bristol is the name of a city, so it needs a capital letter.'],
  [['The old man', 'sat by the window', 'watching the rain', 'and drunk his tea.'], 3,
    'The past tense on its own is "drank". "Drunk" needs "has" or "had" before it.'],
  [['She looked everywhere', 'for her gloves', 'but could not find', 'them nowhere.'], 3,
    'This is a double negative. With "could not" it should be "anywhere".'],
  [['The dog barked loudly', 'at the postman', 'who was walking', 'up the path quick.'], 3,
    'It describes how he walked, so it needs the adverb "quickly".'],
  [['He opened the box', 'very carefully', 'and took out', 'the childrens toys.'], 3,
    '"Children" is already plural, so the possessive is "children\'s toys".'],

  [['After the storm', 'we walked slowly', 'along the beach', 'looking for shells.'], -1,
    'There is no mistake. The comma after the opening phrase is correct.'],
  [['On Saturday morning', 'my dad and I', 'drove to Bristol', 'to see my aunt.'], -1,
    'There is no mistake. The names take capitals and "my dad and I" is right.'],
  [['Neither of the boys', 'was ready', 'when the whistle', 'finally went.'], -1,
    'There is no mistake. "Neither" is singular, so "was ready" is correct.'],
  [['The books that she', 'had ordered last week', 'arrived at the house', 'on Thursday afternoon.'], -1,
    'There is no mistake anywhere in this sentence.'],
];

/** [correctSentence, [four wrong versions], whatMakesItRight] */
export const PUNCTUATED = [
  ['"Where are you going?" asked Mum.',
    ['"Where are you going" asked Mum?', '"Where are you going?" Asked Mum.',
      'Where are you going? asked Mum.', '"Where are you going?", asked Mum.'],
    'The question mark goes inside the speech marks, and "asked" carries on the sentence, so it stays lower case.'],
  ['I packed apples, pears, plums and a bottle of water.',
    ['I packed apples pears plums and a bottle of water.',
      'I packed apples, pears, plums, and, a bottle of water.',
      'I packed, apples, pears, plums and a bottle of water.',
      'I packed apples, pears plums, and a bottle of water.'],
    'Items in a list are separated by commas, and the last two are joined by "and" with no comma.'],
  ['My brother, who is eleven, plays the trumpet.',
    ['My brother who is eleven, plays the trumpet.',
      'My brother, who is eleven plays the trumpet.',
      'My brother who is eleven plays the trumpet,',
      'My brother; who is eleven; plays the trumpet.'],
    'The extra information needs a comma at both ends, like a pair of brackets.'],
  ['It was raining, so we stayed indoors.',
    ['It was raining so, we stayed indoors.', 'It was raining. So we stayed indoors,',
      'It was raining, so, we stayed indoors.', 'It was raining so we stayed indoors,'],
    'The comma goes before the joining word, not after it.'],
  ['"Come inside," said Dad, "before you get soaked."',
    ['"Come inside." said Dad, "before you get soaked."',
      '"Come inside", said Dad "before you get soaked."',
      '"Come inside," Said Dad, "before you get soaked."',
      '"Come inside," said Dad. "before you get soaked."'],
    'The speech is one sentence split in two, so a comma closes the first half and the second half stays lower case.'],
  ['Sam\'s bicycle had a puncture.',
    ['Sams bicycle had a puncture.', 'Sams\' bicycle had a puncture.',
      'Sam\'s bicycle had a puncture\'s.', 'Sam is bicycle had a puncture.'],
    'One person called Sam owns it, so the apostrophe goes before the s.'],
  ['The dogs\' bowls were empty.',
    ['The dogs bowls were empty.', 'The dog\'s bowls were empty\'s.',
      'The dogs bowl\'s were empty.', 'The dog\'s\' bowls were empty.'],
    'More than one dog owns the bowls, so the apostrophe goes after the s.'],
  ['Suddenly, the lights went out.',
    ['Suddenly the lights, went out.', 'Suddenly the lights went out,',
      'Suddenly, the lights, went out.', 'suddenly, the lights went out.'],
    'A comma follows the word that opens the sentence, and the sentence starts with a capital.'],
  ['Have you seen my keys?',
    ['Have you seen my keys.', 'Have you seen my keys!',
      'have you seen my keys?', 'Have you seen my keys'],
    'It is a question, so it takes a question mark, and it starts with a capital letter.'],
  ['We visited London, Cardiff and Belfast.',
    ['We visited london, cardiff and belfast.', 'We visited London Cardiff and Belfast.',
      'We visited, London, Cardiff and Belfast.', 'We visited London, Cardiff, and, Belfast.'],
    'Place names take capitals, and the list needs commas between the first items only.'],
  ['She asked whether we were ready.',
    ['She asked whether we were ready?', '"She asked whether we were ready."',
      'She asked, whether we were ready.', 'She asked whether we were ready!'],
    'This reports a question rather than asking one, so it ends with a full stop.'],
  ['I could not find my coat, my scarf or my gloves.',
    ['I could not find my coat my scarf or my gloves.',
      'I could not find, my coat, my scarf or my gloves.',
      'I could not find my coat, my scarf, or my gloves,',
      'I could not find my coat; my scarf or my gloves.'],
    'Commas separate the items and "or" joins the last two without a comma.'],
  ['We were late, but the film had not started.',
    ['We were late but, the film had not started.',
      'We were late, but, the film had not started.',
      'We were late but the film had not started,',
      'We were late. but the film had not started.'],
    'The comma goes before the joining word "but", not after it.'],
  ['"I have finished!" shouted Amira.',
    ['"I have finished"! shouted Amira.', '"I have finished!" Shouted Amira.',
      'I have finished! shouted Amira.', '"I have finished!", shouted Amira.'],
    'The exclamation mark sits inside the speech marks and "shouted" stays lower case.'],
  ['The cat, which had been asleep, jumped up suddenly.',
    ['The cat which had been asleep, jumped up suddenly.',
      'The cat, which had been asleep jumped up suddenly.',
      'The cat which had been asleep jumped up, suddenly.',
      'The cat, which had been asleep, jumped up suddenly'],
    'The extra information needs a comma at both ends, and the sentence needs a full stop.'],
  ['My mother\'s car would not start this morning.',
    ['My mothers car would not start this morning.',
      'My mothers\' car would not start this morning.',
      'My mother\'s car would not start this morning',
      'my mother\'s car would not start this morning.'],
    'One mother owns the car, so the apostrophe goes before the s.'],
  ['Where did you put the scissors?',
    ['Where did you put the scissors.', 'where did you put the scissors?',
      'Where did you put the scissors!', 'Where, did you put the scissors?'],
    'It asks something, so it needs a question mark, and it starts with a capital.'],
  ['After lunch, we walked to the park.',
    ['After lunch we walked, to the park.', 'After lunch we, walked to the park.',
      'After, lunch we walked to the park.', 'After lunch we walked to the park,'],
    'The comma closes the opening phrase, straight after "lunch".'],
  ['The girls\' changing room was locked.',
    ['The girls changing room was locked.', 'The girl\'s changing room was locked.',
      'The girls changing room\'s was locked.', 'the girls\' changing room was locked.'],
    'More than one girl uses it, so the apostrophe goes after the s.'],
  ['I bought bread, cheese and apples.',
    ['I bought bread cheese and apples.', 'I bought, bread, cheese and apples.',
      'I bought bread, cheese, and, apples.', 'I bought bread, cheese and apples'],
    'Commas separate the items, and "and" joins the last two without a comma.'],
];

/**
 * [words, indexOfWordTheCommaFollows, why]
 * The child picks the word the comma should come after.
 */
export const COMMAS = [
  [['Before', 'the', 'match', 'started', 'we', 'ate', 'our', 'sandwiches.'], 3,
    'The sentence opens with a phrase telling us when, so a comma closes it after "started".'],
  [['Although', 'it', 'was', 'raining', 'we', 'walked', 'to', 'school.'], 3,
    'The opening clause ends at "raining", so the comma goes there.'],
  [['When', 'the', 'bell', 'rang', 'everyone', 'stood', 'up', 'quietly.'], 3,
    'The clause telling us when ends at "rang", so the comma follows it.'],
  [['After', 'a', 'long', 'journey', 'we', 'arrived', 'at', 'the', 'cottage.'], 3,
    'The opening phrase ends at "journey", so the comma goes after it.'],
  [['Slowly', 'and', 'carefully', 'she', 'lifted', 'the', 'lid', 'of', 'the', 'box.'], 2,
    'The words describing how she did it end at "carefully", so the comma follows.'],
  [['If', 'you', 'are', 'ready', 'we', 'can', 'start', 'the', 'game.'], 3,
    'The "if" clause ends at "ready", so the comma goes there.'],
  [['Once', 'the', 'paint', 'was', 'dry', 'we', 'hung', 'the', 'picture', 'up.'], 4,
    'The opening clause ends at "dry", so the comma follows it.'],
  [['In', 'the', 'middle', 'of', 'the', 'night', 'the', 'owl', 'called', 'again.'], 5,
    'The phrase telling us when ends at "night", so the comma goes after it.'],
  [['Because', 'the', 'road', 'was', 'closed', 'the', 'bus', 'took', 'another', 'route.'], 4,
    'The reason clause ends at "closed", so the comma follows it.'],
  [['Without', 'saying', 'a', 'word', 'he', 'picked', 'up', 'his', 'bag', 'and', 'left.'], 3,
    'The opening phrase ends at "word", so the comma goes there.'],
  [['As', 'soon', 'as', 'the', 'rain', 'stopped', 'we', 'went', 'outside.'], 5,
    'The opening clause ends at "stopped", so the comma follows it.'],
  [['Later', 'that', 'evening', 'the', 'lights', 'came', 'back', 'on.'], 2,
    'The phrase telling us when ends at "evening", so the comma goes there.'],
  [['Quietly', 'she', 'closed', 'the', 'door', 'behind', 'her.'], 0,
    'A single opening adverb takes a comma straight after it.'],
  [['While', 'we', 'were', 'waiting', 'for', 'the', 'bus', 'it', 'began', 'to', 'snow.'], 6,
    'The opening clause ends at "bus", so the comma follows it.'],
  [['Every', 'Saturday', 'morning', 'my', 'brother', 'plays', 'football.'], 2,
    'The phrase telling us when ends at "morning", so the comma goes there.'],
  [['Having', 'finished', 'her', 'homework', 'Amira', 'went', 'out', 'to', 'play.'], 3,
    'The opening phrase ends at "homework", so the comma follows it.'],
  [['Unless', 'you', 'hurry', 'we', 'will', 'miss', 'the', 'train.'], 2,
    'The condition ends at "hurry", so the comma goes there.'],
  [['Whenever', 'it', 'snows', 'the', 'school', 'closes', 'early.'], 2,
    'The opening clause ends at "snows", so the comma follows it.'],
  [['Carefully', 'and', 'slowly', 'the', 'nurse', 'lifted', 'his', 'arm.'], 2,
    'The words describing how she did it end at "slowly", so the comma follows.'],
  [['Before', 'you', 'go', 'please', 'lock', 'the', 'door.'], 2,
    'The opening clause ends at "go", so the comma goes there.'],
  [['Although', 'she', 'was', 'tired', 'Priya', 'finished', 'the', 'race.'], 3,
    'The opening clause ends at "tired", so the comma follows it.'],
  [['To', 'reach', 'the', 'castle', 'you', 'must', 'cross', 'a', 'bridge.'], 3,
    'The opening phrase ends at "castle", so the comma goes there.'],
];

/** [sentence with ___, answer, [wrong], why] */
export const GRAMMAR = [
  ['The books on the top shelf ___ very dusty.', 'were', ['was', 'is', 'has', 'been'],
    'The subject is "the books", which is plural, so it takes "were".'],
  ['Each of the players ___ a number on their shirt.', 'has', ['have', 'were', 'are', 'having'],
    '"Each" is singular, so it takes "has".'],
  ['I have ___ that film three times.', 'seen', ['saw', 'see', 'seed', 'seeing'],
    'After "have" the word is "seen". "Saw" is used on its own.'],
  ['She ___ her breakfast before she left.', 'ate', ['eaten', 'eat', 'eats', 'eating'],
    '"Ate" is the past tense on its own. "Eaten" needs "has" or "had" before it.'],
  ['There were ___ cars in the car park than yesterday.', 'fewer', ['less', 'lesser', 'little', 'least'],
    'Cars can be counted, so "fewer" is used rather than "less".'],
  ['The parcel was addressed to my sister and ___.', 'me', ['I', 'myself', 'mine', 'my'],
    'After "to" the word is "me". Try the sentence without "my sister and".'],
  ['___ going to be a long walk home.', 'It is', ['Its', 'It\'s a', 'Its\'', 'It has'],
    '"It is" fits the sentence. The short form "It\'s" would also be right, but "Its" shows belonging.'],
  ['If I ___ taller, I could reach the shelf.', 'were', ['was', 'am', 'be', 'been'],
    'This describes something imagined rather than real, so it takes "were".'],
  ['The dog wagged ___ tail happily.', 'its', ['it\'s', 'its\'', 'their', 'his\''],
    'This shows belonging, and the possessive "its" has no apostrophe.'],
  ['We had ___ the whole cake by teatime.', 'eaten', ['ate', 'eat', 'eating', 'eats'],
    'After "had" the word is "eaten".'],
  ['Neither of the answers ___ correct.', 'was', ['were', 'are', 'have', 'being'],
    '"Neither" is singular, so it takes "was".'],
  ['He ran ___ than anyone else in the race.', 'faster', ['more fast', 'fastest', 'more faster', 'most fast'],
    'Comparing two things takes "faster". "Fastest" compares three or more.'],
  ['This is the ___ book I have ever read.', 'best', ['better', 'goodest', 'more good', 'most best'],
    'Comparing everything he has read takes "best", not "better".'],
  ['She sang ___ than her sister.', 'more sweetly', ['sweeter', 'most sweetly', 'more sweeter', 'sweetliest'],
    'It describes how she sang, so it needs the adverb "more sweetly".'],
  ['The team ___ practising every Thursday.', 'is', ['are being', 'were been', 'has been being', 'be'],
    'The team is treated as one thing here, so it takes "is".'],
  ['I did not tell ___ about the surprise.', 'anyone', ['no one', 'nobody', 'none', 'never'],
    'The sentence already has "not", so a second negative would cancel it out.'],
  ['My coat is older than ___.', 'yours', ['your', 'your\'s', 'yours\'', 'you\'re'],
    'The possessive "yours" never takes an apostrophe.'],
  ['They ___ to the museum last Friday.', 'went', ['gone', 'goed', 'been', 'going'],
    '"Went" is the past tense on its own. "Gone" needs "have" or "had" before it.'],
  ['The girl ___ won the prize is in my class.', 'who', ['which', 'whom', 'whose', 'what'],
    '"Who" is used for a person doing the action.'],
  ['Put the box down over ___.', 'there', ['their', 'they\'re', 'thier', 'theirs'],
    '"There" means that place. "Their" shows belonging.'],
];
